<?php

 $apiKey = "rzp_test_yhi8Khy8vKAD3w";
 include 'mysql_connect.php';

 if($_SERVER["REQUEST_METHOD"] == "POST")
 {

	 $enroll=$_POST['enroll'];
	 $nm=$_POST['name'];
	 $trnid=$_POST['trnid'];
     $trndate=$_POST['date'];
	 $enroll;
	 // Check connection
	if ($conn->connect_error) {
		die("Connection failed: " . $conn->connect_error);
	}

	$sql = "INSERT INTO transaction(trnid, trndate, nam , enrollment) 
	               VALUES ('" . $trnid . "','" . $trndate ."','" . $nm ."','" . $enroll ."')" ;

	if ($conn->query($sql) === TRUE) {
		//echo "New record created successfully";
	} else {
		echo "Error: " . $sql . "<br>" . $conn->error;
	}

	$conn->close();

 }





?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="100" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo $_POST['trnid'];?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Councelling"
    data-description="Counselling"
    data-image="https://traidev.com/img/web-desgin-development.png"
    data-prefill.name="<?php echo $_POST['enroll'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['phone'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

